// Content below is autogenerated by ccsmodule engine
// usually there is no reason to edit it manually
goog.provide(my.style.Main);

goog.require('cssmodule.Stylesheet');

/**
 * @constructor
 * @extends {cssmodule.Stylesheet}
 */
my.style.Main = function() {
  goog.base(this, 'my.style.Main',
      '@media { .counter {\n' +
      '    width: 160px;\n' +
      '    position: absolute;\n' +
      '    top: 81px;\n' +
      '    left: 50%;\n' +
      '    margin-left: 300px;\n' +
      '    overflow: hidden;\n' +
      '    -webkit-transition: top 0.3s ease-out;\n' +
      '     -moz-transition: top 0.3s ease-out;\n' +
      '       -o-transition: top 0.3s ease-out;\n' +
      '        transition: top 0.3s ease-out;\n' +
      '    z-index: 30;\n' +
      '  }\n' +
      '}\n' +
      '.counter-digit {\n' +
      '  display: inline-block;\n' +
      '  vertical-align: middle;\n' +
      '  margin-left: 6px;\n' +
      '}\n' +
      '\n' +
      '.b-found-hotels-counter__label {\n' +
      '  width: 5em;\n' +
      '  display: inline-block;\n' +
      '  vertical-align: middle;\n' +
      '  margin-top: -5px;\n' +
      '  font-size: 11px;\n' +
      '  line-height: 1.2em;\n' +
      '  text-align: right;\n' +
      '  text-shadow: 0px 1px 1px #fff;\n' +
      '  color: #738b9b;\n' +
      '}\n' +
      '\n' +
      '.counter-inner {\n' +
      '  background: url(\'img/clock_countdown.png\') 0 0 no-repeat;\n' +
      '  color: #000;\n' +
      '  display: inline-block;\n' +
      '  font: 22px Arial;\n' +
      '  font-weight: bold;\n' +
      '  height: 36px;\n' +
      '  line-height: 34px;\n' +
      '  margin: 0;\n' +
      '  overflow: hidden;\n' +
      '  padding: 0 3px;\n' +
      '  text-align: center;\n' +
      '  text-shadow: 0 1px 0 rgba(255, 255, 255, 0.5);\n' +
      '  width: 80px;\n' +
      '  white-space: nowrap;\n' +
      '}\n' +
      '\n' +
      '.counter-digit {\n' +
      '  background: url(\'img/counter.png\') 0 22px repeat-y;\n' +
      '  background-image: url(\'img/counter.svg\');\n' +
      '  display: inline-block;\n' +
      '  margin: 0;\n' +
      '  height: 220044px;\n' +
      '  margin: -22px 0 0;\n' +
      '  padding: 0;\n' +
      '  position: relative;\n' +
      '  top: 0;\n' +
      '  vertical-align: top;\n' +
      '  width: 20px;\n' +
      '  \n' +
      '  -webkit-transition: all 500ms cubic-bezier(0.075, 0.820, 0.165, 1.000); \n' +
      '     -moz-transition: all 500ms cubic-bezier(0.075, 0.820, 0.165, 1.000); \n' +
      '      -ms-transition: all 500ms cubic-bezier(0.075, 0.820, 0.165, 1.000); \n' +
      '       -o-transition: all 500ms cubic-bezier(0.075, 0.820, 0.165, 1.000); \n' +
      '          transition: all 500ms cubic-bezier(0.075, 0.820, 0.165, 1.000); /* easeOutCirc */\n' +
      '}\n' +
      '\n' +
      '.counter-digit-item {\n' +
      '  display: none;\n' +
      '  font: 22px Arial;\n' +
      '  font-weight: bold;\n' +
      '  line-height: 22px;\n' +
      '  margin: 0;\n' +
      '  padding: 0;\n' +
      '}\n' +
      '\n' +
      '.counter-label {\n' +
      '  color: #738b9b;\n' +
      '  display: inline-block;\n' +
      '  font-size: 11px;\n' +
      '  line-height: 1.2em;\n' +
      '  margin: -5px 2ex 0 0;\n' +
      '  text-align: right;\n' +
      '  text-shadow: 0 1px 1px #fff;\n' +
      '  vertical-align: middle;\n' +
      '  width: 5em;\n' +
      '}\n' +
      '',
     '');
};
goog.inherits(my.style.Main, cssmodule.Stylesheet);
